image: node:10.12.0 # can be upgraded, depending on your node version used

before_script:
  - apt update
  - apt install -y rsync
  - npm install
 
build:
  stage: build
  script:
  - npm run build
  - rm -rf public
  - mv build public
  only:
  - master # or dev, the branch you want to publish

deploy:
  artifacts:
    paths:
    - public # mandatory, other folder won't work
    expire_in: 1 day
  stage: deploy
  script:
  - rsync -r ./public/*  rsync://admin@92.53.77.8/html