image: node:10.12.0 # can be upgraded, depending on your node version used


 
build:
  stage: build
  script:
  - npm install
  - npm run build
  - rm -rf public
  - mv build public
  artifacts:
    paths:
    - public
    expire_in: 1 day
  only:
  - master # or dev, the branch you want to publish

deploy:
  image: eeacms/rsync
  stage: deploy
  script:
  - rsync -r ./public/*  rsync://admin@92.53.77.8/html