image: node:10.12.0 # can be upgraded, depending on your node version used
 
build:
  cache:
    paths:
    - node_modules/
 
  stage: build
  script:
  - npm install
  - npm run build
  - rm -rf public
  - mv build public
  artifacts:
    paths:
    - public # mandatory, other folder won't work
    expire_in: 1 hour
  only:
  - master # or dev, the branch you want to publish
deploy:
  type: deploy
  script:
    sync -a ~/build admin@92.53.77.8:html